<a href="https://colab.research.google.com/github/chaitanya3323/Gitcodes/blob/master/intro_to_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [14]:
a=tf.Variable(34)
b=tf.Variable(23)
tf.add(a,b,name='sum')

<tf.Tensor: shape=(), dtype=int32, numpy=57>

In [15]:
print(sum)

tf.Tensor(57, shape=(), dtype=int32)


In [16]:
sum.numpy()

57

In [17]:
print(sum)

tf.Tensor(57, shape=(), dtype=int32)


In [18]:
sum

<tf.Tensor: shape=(), dtype=int32, numpy=57>

In [23]:
multiplication=tf.multiply(a,b,name='multiplication')

In [24]:
print(multiplication)

tf.Tensor(782, shape=(), dtype=int32)


In [25]:
sub=tf.subtract(a,b)

In [26]:
print(sub)

tf.Tensor(11, shape=(), dtype=int32)


## Computational graphs with @tf.function

In [29]:
@tf.function
def func(a,b):
  z=tf.multiply(a,b)
  y1=tf.constant(3)
  y2=tf.constant(4)
  w1=tf.add(z,y1)
  w2=tf.add(z,y2)

  return (w1+w2)

In [30]:
func(10,20)

<tf.Tensor: shape=(), dtype=int32, numpy=407>

#Calculating gradient

In [35]:
w=tf.Variable(3.0)

with tf.GradientTape() as tape:
  expression=tf.exp(w)+2*w +w*w

grad=tape.gradient(expression,w)#first argument for the expression to differentiate and secomd for with respect to what you have to dffrentiate
print(f'The gradient of exp at {w.numpy()} is {grad.numpy()}')


The gradient of exp at 3.0 is 28.08553695678711


# similarly we can use it for sigmoid function